/**
 * Learning Tracks Mock Data
 *
 * To adjust categories: modify learningCategories array
 * To add/modify tracks: modify learningTracks array
 * Each track should have 4-8 modules with Portuguese copy
 * Cover images use Unsplash URLs for realistic imagery
 */

import { LearningTrack, LearningModule, TrackCategory } from "@/types";

// Unsplash images for tracks (barber/salon/professional context)
// High quality images optimized for hero carousel (w=1920 for better quality on large screens)
export const trackImages = {
  rapport: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1920&q=90&auto=format&fit=crop",
  confianca: "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=1920&q=90&auto=format&fit=crop",
  perguntas: "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=1920&q=90&auto=format&fit=crop",
  cliente: "https://images.unsplash.com/photo-1582095133179-bfd08e2fc6b3?w=1920&q=90&auto=format&fit=crop",
  objecoes: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1920&q=90&auto=format&fit=crop",
  persuasao: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=1920&q=90&auto=format&fit=crop",
  upselling: "https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=1920&q=90&auto=format&fit=crop",
  fidelidade: "https://images.unsplash.com/photo-1622286342621-4bd786c2447c?w=1920&q=90&auto=format&fit=crop",
  reativacao: "https://images.unsplash.com/photo-1493256338651-d82f7acb2b38?w=1920&q=90&auto=format&fit=crop",
  reclamacoes: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=1920&q=90&auto=format&fit=crop",
  fechamento: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1920&q=90&auto=format&fit=crop",
  dinheiro: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1920&q=90&auto=format&fit=crop",
};

// Module images (optimized for card displays)
export const moduleImages = {
  comunicacao: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&q=85&auto=format&fit=crop",
  escuta: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&q=85&auto=format&fit=crop",
  atendimento: "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=800&q=85&auto=format&fit=crop",
  negociacao: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&q=85&auto=format&fit=crop",
  vendas: "https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?w=800&q=85&auto=format&fit=crop",
  produto: "https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=800&q=85&auto=format&fit=crop",
  cliente: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&q=85&auto=format&fit=crop",
  feedback: "https://images.unsplash.com/photo-1531545514256-b1400bc00f31?w=800&q=85&auto=format&fit=crop",
};

// 3 categories for barber seller persona
export const learningCategories: TrackCategory[] = [
  {
    id: "cat-1",
    slug: "cumprimento-rapport",
    name: "Cumprimento e Rapport com o Cliente",
    description: "Técnicas para criar conexão inicial e construir confiança",
    order: 1,
  },
  {
    id: "cat-2",
    slug: "descoberta-necessidades",
    name: "Descoberta de Necessidades",
    description: "Como identificar o que o cliente realmente precisa",
    order: 2,
  },
  {
    id: "cat-3",
    slug: "lidando-objecoes",
    name: "Lidando com Objeções",
    description: "Estratégias para superar resistências e dúvidas",
    order: 3,
  },
];

// 18 tracks total (6 per category, 3 categories)
export const learningTracks: LearningTrack[] = [
  // Category 1: Cumprimento e Rapport (6 tracks)
  {
    id: "track-1",
    slug: "primeira-impressao-perfeita",
    title: "Primeira Impressão Perfeita",
    description: "Aprenda a criar uma conexão imediata com seus clientes desde o primeiro contato. Técnicas de linguagem corporal, tom de voz e abordagem inicial.",
    coverImage: trackImages.rapport,
    estimatedTime: "45 min",
    difficulty: "beginner",
    badge: "beginner",
    categoryId: "cat-1",
    progress: 0,
    tags: ["rapport", "comunicação", "iniciante"],
    featured: true,
    modules: [
      {
        id: "mod-1-1",
        title: "O Poder do Sorriso e Contato Visual",
        objective: "Dominar técnicas de linguagem corporal para criar acolhimento",
        content:
          "Neste módulo você verá exemplos práticos de como o sorriso e o contato visual transmitem confiança desde o primeiro momento. Inclui demonstrações de abertura de atendimento, postura e tom de voz adequados, e como evitar gestos que geram desconfiança. Ao final, você terá clareza sobre o que fazer nos primeiros segundos de contato com o cliente.",
        duration: "8 min",
        status: "not_started",
        order: 1,
        scenarioSlug: "atendimento",
        characterId: "char-1",
      },
      {
        id: "mod-1-2",
        title: "Cumprimento Personalizado",
        objective: "Adaptar sua abordagem ao perfil do cliente",
        content:
          "Aqui você aprende a identificar rapidamente o perfil do cliente (mais formal ou descontraído, apressado ou receptivo) e a ajustar seu cumprimento e linguagem. O conteúdo traz cenários reais de abordagem inicial, frases que funcionam para cada perfil e como evitar erros comuns que afastam o cliente antes mesmo da venda.",
        duration: "10 min",
        status: "not_started",
        order: 2,
        scenarioSlug: "atendimento",
        characterId: "char-2",
      },
      {
        id: "mod-1-3",
        title: "Quebra-gelos Eficientes",
        objective: "Iniciar conversas naturais que criam conexão",
        duration: "12 min",
        status: "not_started",
        order: 3,
        scenarioSlug: "atendimento",
        characterId: "char-3",
      },
      {
        id: "mod-1-4",
        title: "Leitura do Cliente",
        objective: "Identificar o humor e disposição do cliente",
        duration: "15 min",
        status: "not_started",
        order: 4,
        scenarioSlug: "atendimento",
        characterId: "char-1",
      },
    ],
  },
  {
    id: "track-2",
    slug: "construindo-confianca",
    title: "Construindo Confiança em Minutos",
    description: "Técnicas avançadas para estabelecer credibilidade e confiança rapidamente com diferentes perfis de clientes.",
    coverImage: trackImages.confianca,
    estimatedTime: "1h 10min",
    difficulty: "intermediate",
    badge: "popular",
    categoryId: "cat-1",
    progress: 30,
    tags: ["confiança", "credibilidade", "relacionamento"],
    featured: true,
    modules: [
      {
        id: "mod-2-1",
        title: "Espelhamento Natural",
        objective: "Usar técnicas de espelhamento sem parecer artificial",
        content:
          "O módulo explica como espelhar sutilmente a postura, o ritmo da fala e até o vocabulário do cliente para criar rapport. Você verá vídeos comparando espelhamento natural e forçado, dicas de timing e como aplicar a técnica em atendimento presencial e por vídeo sem que o cliente perceba de forma negativa.",
        duration: "12 min",
        status: "completed",
        order: 1,
        scenarioSlug: "atendimento",
        characterId: "char-2",
      },
      {
        id: "mod-2-2",
        title: "Demonstrando Expertise",
        objective: "Mostrar conhecimento sem ser arrogante",
        content:
          "Conteúdo focado em como comunicar sua experiência e conhecimento de forma que o cliente se sinta seguro, sem soar superior ou condescendente. Inclui frases que funcionam, tom de voz, quando usar casos de sucesso e como responder a dúvidas técnicas mantendo autoridade e acessibilidade.",
        duration: "15 min",
        status: "in_progress",
        order: 2,
        scenarioSlug: "venda-b2b",
        characterId: "char-1",
      },
      {
        id: "mod-2-3",
        title: "Escuta Ativa Avançada",
        objective: "Técnicas de escuta que fazem o cliente se sentir ouvido",
        duration: "13 min",
        status: "not_started",
        order: 3,
        scenarioSlug: "atendimento",
        characterId: "char-3",
      },
      {
        id: "mod-2-4",
        title: "Lidando com Clientes Desconfiados",
        objective: "Estratégias para clientes céticos ou reservados",
        duration: "15 min",
        status: "not_started",
        order: 4,
        scenarioSlug: "negociacao",
        characterId: "char-2",
      },
      {
        id: "mod-2-5",
        title: "Prática: Cenários de Confiança",
        objective: "Roleplay com diferentes perfis de clientes",
        duration: "15 min",
        status: "not_started",
        order: 5,
        scenarioSlug: "atendimento",
        characterId: "char-1",
      },
    ],
  },
  {
    id: "track-1-3",
    slug: "comunicacao-eficaz",
    title: "Comunicação Eficaz com Clientes",
    description: "Desenvolva habilidades de comunicação que criam conexão genuína e facilitam o relacionamento com diferentes perfis de clientes.",
    coverImage: trackImages.rapport,
    estimatedTime: "50 min",
    difficulty: "beginner",
    categoryId: "cat-1",
    progress: 0,
    tags: ["comunicação", "rapport", "relacionamento"],
    modules: [
      {
        id: "mod-1-3-1",
        title: "Fundamentos da Comunicação",
        objective: "Entender os pilares da comunicação eficaz",
        content:
          "Este módulo apresenta os quatro pilares da comunicação eficaz: clareza, empatia, escuta ativa e feedback. Você verá exemplos de como cada um se aplica no atendimento ao cliente e como pequenos ajustes na forma de falar e ouvir podem melhorar drasticamente o resultado da conversa e da venda.",
        duration: "10 min",
        status: "not_started",
        order: 1,
        scenarioSlug: "atendimento",
        characterId: "char-1",
      },
      {
        id: "mod-1-3-2",
        title: "Tom de Voz e Entonação",
        objective: "Usar a voz como ferramenta de conexão",
        content:
          "Aqui você aprende a variar o tom e a entonação para transmitir confiança, interesse e calma. O conteúdo inclui exercícios práticos de respiração e fala, comparações entre tons que afastam e que aproximam o cliente, e como adaptar sua voz ao contexto (presencial, telefone, vídeo).",
        duration: "12 min",
        status: "not_started",
        order: 2,
        scenarioSlug: "atendimento",
        characterId: "char-2",
      },
      {
        id: "mod-1-3-3",
        title: "Linguagem Corporal Positiva",
        objective: "Transmitir confiança através do corpo",
        duration: "15 min",
        status: "not_started",
        order: 3,
        scenarioSlug: "atendimento",
        characterId: "char-3",
      },
      {
        id: "mod-1-3-4",
        title: "Prática de Comunicação",
        objective: "Roleplay de diferentes cenários",
        duration: "13 min",
        status: "not_started",
        order: 4,
        scenarioSlug: "atendimento",
        characterId: "char-1",
      },
    ],
  },
  {
    id: "track-1-4",
    slug: "criando-ambiente-acolhedor",
    title: "Criando um Ambiente Acolhedor",
    description: "Aprenda a transformar o espaço físico e emocional da sua barbearia em um ambiente que faz o cliente se sentir em casa.",
    coverImage: trackImages.confianca,
    estimatedTime: "40 min",
    difficulty: "beginner",
    categoryId: "cat-1",
    progress: 0,
    tags: ["ambiente", "acolhimento", "experiência"],
    modules: [
      {
        id: "mod-1-4-1",
        title: "Primeiros Momentos",
        objective: "Criar impacto positivo nos primeiros segundos",
        content:
          "O módulo detalha tudo o que acontece nos primeiros 30 segundos do contato: recepção, cumprimento, oferta de bebida ou conforto e tom da conversa inicial. Você verá checklists práticos e vídeos de bons e maus exemplos para garantir que cada cliente se sinta bem-vindo desde a porta.",
        duration: "10 min",
        status: "not_started",
        order: 1,
        scenarioSlug: "atendimento",
        characterId: "char-1",
      },
      {
        id: "mod-1-4-2",
        title: "Ambiente Físico",
        objective: "Organizar o espaço para conforto",
        content:
          "Conteúdo sobre iluminação, temperatura, organização do espaço e pequenos detalhes que fazem o cliente relaxar (revistas, água, música). Inclui dicas de baixo custo para melhorar o ambiente e como alinhar o visual do local ao público que você atende.",
        duration: "8 min",
        status: "not_started",
        order: 2,
        scenarioSlug: "atendimento",
        characterId: "char-2",
      },
      {
        id: "mod-1-4-3",
        title: "Criando Conexão Rápida",
        objective: "Técnicas para conexão imediata",
        duration: "12 min",
        status: "not_started",
        order: 3,
        scenarioSlug: "atendimento",
        characterId: "char-3",
      },
      {
        id: "mod-1-4-4",
        title: "Prática de Acolhimento",
        objective: "Roleplay de diferentes situações",
        duration: "10 min",
        status: "not_started",
        order: 4,
        scenarioSlug: "atendimento",
        characterId: "char-1",
      },
    ],
  },
  {
    id: "track-1-5",
    slug: "rapport-avancado",
    title: "Rapport Avançado",
    description: "Técnicas sofisticadas para criar conexão profunda e duradoura com clientes, indo além do básico.",
    coverImage: trackImages.confianca,
    estimatedTime: "1h",
    difficulty: "intermediate",
    categoryId: "cat-1",
    progress: 0,
    tags: ["rapport", "conexão", "avançado"],
    modules: [
      {
        id: "mod-1-5-1",
        title: "Espelhamento Avançado",
        objective: "Técnicas de espelhamento sutil",
        content:
          "Este módulo aprofunda o espelhamento: além de postura e gestos, você verá como espelhar ritmo de fala, pausas e até escolhas de palavras. Inclui exemplos de espelhamento em vídeo e presencial, quando intensificar ou suavizar, e como evitar que a técnica pareça forçada ou irônica.",
        duration: "15 min",
        status: "not_started",
        order: 1,
        scenarioSlug: "atendimento",
        characterId: "char-1",
      },
      {
        id: "mod-1-5-2",
        title: "Sincronização",
        objective: "Sincronizar ritmo e energia",
        content:
          "Aqui você aprende a sincronizar seu ritmo e energia com o do cliente: velocidade da fala, nível de entusiasmo e tom emocional. O conteúdo traz exercícios práticos e como calibrar a sincronização em clientes mais reservados ou mais animados para manter o rapport sem perder autenticidade.",
        duration: "12 min",
        status: "not_started",
        order: 2,
        scenarioSlug: "atendimento",
        characterId: "char-2",
      },
      {
        id: "mod-1-5-3",
        title: "Criando Memórias",
        objective: "Fazer o cliente se lembrar de você",
        duration: "18 min",
        status: "not_started",
        order: 3,
        scenarioSlug: "atendimento",
        characterId: "char-3",
      },
      {
        id: "mod-1-5-4",
        title: "Prática Avançada",
        objective: "Roleplay de rapport avançado",
        duration: "15 min",
        status: "not_started",
        order: 4,
        scenarioSlug: "atendimento",
        characterId: "char-1",
      },
    ],
  },
  {
    id: "track-1-6",
    slug: "primeiro-contato-perfeito",
    title: "Primeiro Contato Perfeito",
    description: "Domine a arte do primeiro contato, criando uma impressão memorável desde o primeiro segundo de interação.",
    coverImage: trackImages.rapport,
    estimatedTime: "35 min",
    difficulty: "beginner",
    categoryId: "cat-1",
    progress: 0,
    tags: ["primeiro contato", "impressão", "iniciante"],
    modules: [
      {
        id: "mod-1-6-1",
        title: "Os Primeiros 30 Segundos",
        objective: "Criar impacto nos primeiros momentos",
        content:
          "O módulo detalha segundo a segundo o que fazer nos primeiros 30 segundos: recepção, contato visual, cumprimento e primeira frase. Você verá vídeos comparando abordagens que geram confiança e as que geram desconfiança, e um checklist para revisar antes de cada atendimento.",
        duration: "8 min",
        status: "not_started",
        order: 1,
        scenarioSlug: "atendimento",
        characterId: "char-1",
      },
      {
        id: "mod-1-6-2",
        title: "Cumprimentos Eficazes",
        objective: "Diferentes formas de cumprimentar",
        content:
          "Conteúdo sobre as diferentes formas de cumprimentar: formal e informal, com e sem contato físico, e como escolher de acordo com o perfil do cliente e o contexto. Inclui frases prontas para cada situação e como evitar cumprimentos que soam falsos ou invasivos.",
        duration: "10 min",
        status: "not_started",
        order: 2,
        scenarioSlug: "atendimento",
        characterId: "char-2",
      },
      {
        id: "mod-1-6-3",
        title: "Quebra-gelos Rápidos",
        objective: "Iniciar conversas naturalmente",
        duration: "9 min",
        status: "not_started",
        order: 3,
        scenarioSlug: "atendimento",
        characterId: "char-3",
      },
      {
        id: "mod-1-6-4",
        title: "Prática de Primeiro Contato",
        objective: "Roleplay de diferentes situações",
        duration: "8 min",
        status: "not_started",
        order: 4,
        scenarioSlug: "atendimento",
        characterId: "char-1",
      },
    ],
  },

  // Category 2: Descoberta de Necessidades (6 tracks)
  {
    id: "track-3",
    slug: "perguntas-poderosas",
    title: "A Arte das Perguntas Poderosas",
    description: "Domine a técnica de fazer perguntas que revelam as verdadeiras necessidades e desejos dos clientes.",
    coverImage: trackImages.perguntas,
    estimatedTime: "55 min",
    difficulty: "beginner",
    badge: "recommended",
    categoryId: "cat-2",
    progress: 0,
    tags: ["perguntas", "necessidades", "descoberta"],
    featured: true,
    modules: [
      {
        id: "mod-3-1",
        title: "Perguntas Abertas vs Fechadas",
        objective: "Quando usar cada tipo de pergunta",
        content:
          "Neste módulo você verá a diferença entre perguntas abertas (que geram reflexão e detalhes) e fechadas (que confirmam e direcionam), quando usar cada tipo na venda e como evitar sequências que soam interrogatórias. Inclui listas de exemplos prontos para cada etapa da descoberta.",
        duration: "10 min",
        status: "not_started",
        order: 1,
        scenarioSlug: "venda-b2b",
        characterId: "char-1",
      },
      {
        id: "mod-3-2",
        title: "Técnica do Funil",
        objective: "Conduzir a conversa do geral para o específico",
        content:
          "Aqui você aprende a conduzir a conversa do geral para o específico: começar com contexto amplo, depois problema atual, consequências e desejos. O conteúdo traz a ordem ideal das perguntas, como fazer transições naturais e como não pular etapas que prejudicam o diagnóstico.",
        duration: "12 min",
        status: "not_started",
        order: 2,
        scenarioSlug: "venda-b2b",
        characterId: "char-2",
      },
      {
        id: "mod-3-3",
        title: "Descobrindo Motivações Ocultas",
        objective: "Identificar o que realmente importa para o cliente",
        duration: "15 min",
        status: "not_started",
        order: 3,
        scenarioSlug: "negociacao",
        characterId: "char-3",
      },
      {
        id: "mod-3-4",
        title: "Prática de Diagnóstico",
        objective: "Roleplay de descoberta de necessidades",
        duration: "18 min",
        status: "not_started",
        order: 4,
        scenarioSlug: "venda-b2b",
        characterId: "char-1",
      },
    ],
  },
  {
    id: "track-4",
    slug: "entendendo-cliente-profundamente",
    title: "Entendendo o Cliente Profundamente",
    description: "Vá além do superficial e aprenda a identificar padrões, preferências e expectativas não ditas.",
    coverImage: trackImages.cliente,
    estimatedTime: "1h 20min",
    difficulty: "advanced",
    badge: "new",
    categoryId: "cat-2",
    progress: 0,
    tags: ["perfil", "análise", "avançado"],
    modules: [
      {
        id: "mod-4-1",
        title: "Perfis de Personalidade",
        objective: "Identificar os 4 principais perfis de clientes",
        content:
          "O módulo apresenta os quatro perfis mais usados em vendas (analítico, expressivo, amigável, direto): características, como reconhecê-los rapidamente e como adaptar sua abordagem para cada um. Você verá exemplos de clientes reais e erros comuns ao tratar todos do mesmo jeito.",
        duration: "15 min",
        status: "not_started",
        order: 1,
        scenarioSlug: "atendimento",
        characterId: "char-1",
      },
      {
        id: "mod-4-2",
        title: "Sinais Não-Verbais",
        objective: "Ler a linguagem corporal do cliente",
        content:
          "Conteúdo sobre postura, braços cruzados, contato visual, inclinação do corpo e microexpressões que indicam interesse, dúvida ou resistência. Inclui como não interpretar demais um único gesto e como combinar sinais verbais e não verbais para ler o cliente com mais precisão.",
        duration: "12 min",
        status: "not_started",
        order: 2,
        scenarioSlug: "negociacao",
        characterId: "char-2",
      },
      {
        id: "mod-4-3",
        title: "Histórico e Contexto",
        objective: "Usar informações passadas para personalizar",
        duration: "10 min",
        status: "not_started",
        order: 3,
        scenarioSlug: "atendimento",
        characterId: "char-3",
      },
      {
        id: "mod-4-4",
        title: "Adaptação de Abordagem",
        objective: "Ajustar seu estilo ao perfil do cliente",
        duration: "15 min",
        status: "not_started",
        order: 4,
        scenarioSlug: "venda-b2b",
        characterId: "char-1",
      },
      {
        id: "mod-4-5",
        title: "Cenários Complexos",
        objective: "Prática com clientes difíceis de ler",
        duration: "18 min",
        status: "not_started",
        order: 5,
        scenarioSlug: "negociacao",
        characterId: "char-2",
      },
      {
        id: "mod-4-6",
        title: "Avaliação Final",
        objective: "Teste seus conhecimentos de análise",
        duration: "10 min",
        status: "not_started",
        order: 6,
        scenarioSlug: "atendimento",
        characterId: "char-3",
      },
    ],
  },
  {
    id: "track-2-3",
    slug: "tecnicas-perguntas",
    title: "Técnicas de Perguntas Estratégicas",
    description: "Aprenda a fazer perguntas que revelam informações valiosas sobre o cliente e suas necessidades reais.",
    coverImage: trackImages.perguntas,
    estimatedTime: "55 min",
    difficulty: "intermediate",
    categoryId: "cat-2",
    progress: 0,
    tags: ["perguntas", "estratégia", "descoberta"],
    modules: [
      {
        id: "mod-2-3-1",
        title: "Tipos de Perguntas",
        objective: "Conhecer diferentes tipos de perguntas",
        content:
          "Este módulo detalha os tipos de perguntas usados em descoberta: abertas, fechadas, de reflexão, de impacto e de confirmação. Você verá quando usar cada tipo, exemplos de formulação e como evitar perguntas que levam a respostas superficiais ou defensivas.",
        duration: "12 min",
        status: "not_started",
        order: 1,
        scenarioSlug: "venda-b2b",
        characterId: "char-1",
      },
      {
        id: "mod-2-3-2",
        title: "Sequência de Perguntas",
        objective: "Criar fluxo natural de perguntas",
        content:
          "Aqui você aprende a montar uma sequência de perguntas que flui naturalmente: do contexto geral para o problema, depois consequências e desejos. O conteúdo traz modelos de funil por tipo de venda e como encaixar as perguntas na conversa sem parecer roteiro.",
        duration: "15 min",
        status: "not_started",
        order: 2,
        scenarioSlug: "venda-b2b",
        characterId: "char-2",
      },
      {
        id: "mod-2-3-3",
        title: "Perguntas Poderosas",
        objective: "Perguntas que geram insights",
        duration: "13 min",
        status: "not_started",
        order: 3,
        scenarioSlug: "negociacao",
        characterId: "char-3",
      },
      {
        id: "mod-2-3-4",
        title: "Prática de Perguntas",
        objective: "Roleplay de descoberta",
        duration: "15 min",
        status: "not_started",
        order: 4,
        scenarioSlug: "venda-b2b",
        characterId: "char-1",
      },
    ],
  },
  {
    id: "track-2-4",
    slug: "identificando-padroes",
    title: "Identificando Padrões do Cliente",
    description: "Desenvolva a habilidade de identificar padrões de comportamento e preferências que revelam necessidades não expressas.",
    coverImage: trackImages.cliente,
    estimatedTime: "1h 10min",
    difficulty: "intermediate",
    categoryId: "cat-2",
    progress: 0,
    tags: ["padrões", "análise", "comportamento"],
    modules: [
      {
        id: "mod-2-4-1",
        title: "Observação Atenta",
        objective: "Aprender a observar detalhes importantes",
        content:
          "O módulo ensina a observar detalhes que revelam preferências e objeções: como o cliente se senta, o que toca, o que evita, tom de voz e pausas. Você verá exercícios de observação em vídeo e como anotar mentalmente sem perder o foco na conversa.",
        duration: "15 min",
        status: "not_started",
        order: 1,
        scenarioSlug: "atendimento",
        characterId: "char-1",
      },
      {
        id: "mod-2-4-2",
        title: "Sinais Não-Verbais",
        objective: "Ler a linguagem corporal",
        content:
          "Conteúdo sobre postura, gestos, contato visual e expressões que indicam abertura ou resistência. Inclui como calibrar sua leitura (evitar interpretar um único gesto) e como combinar sinais verbais e não verbais para entender melhor o cliente.",
        duration: "18 min",
        status: "not_started",
        order: 2,
        scenarioSlug: "negociacao",
        characterId: "char-2",
      },
      {
        id: "mod-2-4-3",
        title: "Padrões de Comportamento",
        objective: "Identificar padrões recorrentes",
        duration: "20 min",
        status: "not_started",
        order: 3,
        scenarioSlug: "atendimento",
        characterId: "char-3",
      },
      {
        id: "mod-2-4-4",
        title: "Prática de Observação",
        objective: "Roleplay de análise",
        duration: "17 min",
        status: "not_started",
        order: 4,
        scenarioSlug: "venda-b2b",
        characterId: "char-1",
      },
    ],
  },
  {
    id: "track-2-5",
    slug: "necessidades-ocultas",
    title: "Descobrindo Necessidades Ocultas",
    description: "Vá além do óbvio e aprenda a identificar necessidades que o cliente nem sabe que tem.",
    coverImage: trackImages.cliente,
    estimatedTime: "1h 15min",
    difficulty: "advanced",
    categoryId: "cat-2",
    progress: 0,
    tags: ["necessidades", "ocultas", "avançado"],
    modules: [
      {
        id: "mod-2-5-1",
        title: "Necessidades vs Desejos",
        objective: "Diferenciar necessidades reais de desejos",
        content:
          "Neste módulo você aprende a separar o que o cliente diz que quer do que realmente precisa: necessidades funcionais, emocionais e de status. O conteúdo traz perguntas que revelam motivações ocultas e como usar essa distinção para propor a solução certa e fechar com mais consistência.",
        duration: "18 min",
        status: "not_started",
        order: 1,
        scenarioSlug: "venda-b2b",
        characterId: "char-1",
      },
      {
        id: "mod-2-5-2",
        title: "Técnicas de Escavação",
        objective: "Perguntas que revelam camadas profundas",
        content:
          "Aqui você vê técnicas de aprofundamento: perguntas em camadas (por quê, e o que isso significa para você, o que acontece se não resolver), silêncio estratégico e paráfrase que gera mais reflexão. Inclui exemplos de conversas reais e como não soar invasivo.",
        duration: "20 min",
        status: "not_started",
        order: 2,
        scenarioSlug: "negociacao",
        characterId: "char-2",
      },
      {
        id: "mod-2-5-3",
        title: "Lendo Entre as Linhas",
        objective: "Interpretar o que não é dito",
        duration: "17 min",
        status: "not_started",
        order: 3,
        scenarioSlug: "atendimento",
        characterId: "char-3",
      },
      {
        id: "mod-2-5-4",
        title: "Prática Avançada",
        objective: "Roleplay de descoberta profunda",
        duration: "20 min",
        status: "not_started",
        order: 4,
        scenarioSlug: "venda-b2b",
        characterId: "char-1",
      },
    ],
  },
  {
    id: "track-2-6",
    slug: "mapeamento-perfil",
    title: "Mapeamento de Perfil do Cliente",
    description: "Aprenda a criar um perfil completo do cliente através de perguntas estratégicas e observação cuidadosa.",
    coverImage: trackImages.cliente,
    estimatedTime: "50 min",
    difficulty: "intermediate",
    categoryId: "cat-2",
    progress: 0,
    tags: ["perfil", "mapeamento", "cliente"],
    modules: [
      {
        id: "mod-2-6-1",
        title: "Estrutura de Mapeamento",
        objective: "Criar sistema de mapeamento",
        content:
          "O módulo apresenta uma estrutura simples para mapear o cliente: contexto, papel, objetivos, dores, objeções e critérios de decisão. Você verá um checklist utilizável em qualquer venda e como preencher cada bloco com perguntas e observação sem transformar a reunião em questionário.",
        duration: "12 min",
        status: "not_started",
        order: 1,
        scenarioSlug: "atendimento",
        characterId: "char-1",
      },
      {
        id: "mod-2-6-2",
        title: "Informações Essenciais",
        objective: "Identificar o que realmente importa",
        content:
          "Aqui você aprende a priorizar quais informações coletar primeiro: papel na decisão, prazo, orçamento e critérios de sucesso. O conteúdo traz perguntas diretas e indiretas para cada item e como encaixá-las na conversa sem soar como checklist.",
        duration: "13 min",
        status: "not_started",
        order: 2,
        scenarioSlug: "venda-b2b",
        characterId: "char-2",
      },
      {
        id: "mod-2-6-3",
        title: "Construindo o Perfil",
        objective: "Organizar informações coletadas",
        duration: "15 min",
        status: "not_started",
        order: 3,
        scenarioSlug: "negociacao",
        characterId: "char-3",
      },
      {
        id: "mod-2-6-4",
        title: "Prática de Mapeamento",
        objective: "Roleplay completo de mapeamento",
        duration: "10 min",
        status: "not_started",
        order: 4,
        scenarioSlug: "atendimento",
        characterId: "char-1",
      },
    ],
  },

  // Category 3: Lidando com Objeções (6 tracks)
  {
    id: "track-5",
    slug: "objecoes-comuns-barbearia",
    title: "Objeções Comuns na Barbearia",
    description: "Aprenda a lidar com as objeções mais frequentes como preço, tempo de espera e preferências de estilo.",
    coverImage: trackImages.objecoes,
    estimatedTime: "50 min",
    difficulty: "intermediate",
    badge: "popular",
    categoryId: "cat-3",
    progress: 60,
    tags: ["objeções", "preço", "negociação"],
    featured: true,
    modules: [
      {
        id: "mod-5-1",
        title: "A Objeção do Preço",
        objective: "Responder quando o cliente acha caro",
        content:
          "Neste módulo você verá como responder à objeção de preço sem descontar: reforçar valor, quebrar em custo por uso ou por tempo, e comparar com alternativas. Inclui frases prontas, quando usar prova social e como evitar respostas defensivas que pioram a objeção.",
        duration: "12 min",
        status: "completed",
        order: 1,
        scenarioSlug: "negociacao",
        characterId: "char-1",
      },
      {
        id: "mod-5-2",
        title: "Tempo de Espera",
        objective: "Gerenciar expectativas de tempo",
        content:
          "O conteúdo ensina a gerenciar a objeção de espera: comunicar tempo realista, oferecer alternativas (horário, agendamento) e transformar a espera em valor (ex.: ambiente, café). Você verá scripts para diferentes situações e como evitar promessas que não pode cumprir.",
        duration: "10 min",
        status: "completed",
        order: 2,
        scenarioSlug: "atendimento",
        characterId: "char-2",
      },
      {
        id: "mod-5-3",
        title: "Estilo Diferente do Pedido",
        objective: "Quando o resultado não é o esperado",
        duration: "13 min",
        status: "completed",
        order: 3,
        scenarioSlug: "atendimento",
        characterId: "char-3",
      },
      {
        id: "mod-5-4",
        title: "Técnica Feel-Felt-Found",
        objective: "Framework clássico para objeções",
        duration: "15 min",
        status: "not_started",
        order: 4,
        scenarioSlug: "negociacao",
        characterId: "char-1",
      },
    ],
  },
  {
    id: "track-6",
    slug: "virar-nao-em-sim",
    title: "Como Virar um 'Não' em 'Sim'",
    description: "Técnicas avançadas de persuasão ética para transformar resistência em aceitação.",
    coverImage: trackImages.persuasao,
    estimatedTime: "1h 5min",
    difficulty: "advanced",
    categoryId: "cat-3",
    progress: 0,
    tags: ["persuasão", "negociação", "avançado"],
    modules: [
      {
        id: "mod-6-1",
        title: "Entendendo a Resistência",
        objective: "Por que clientes dizem não",
        content:
          "O módulo explica as causas mais comuns de resistência: medo de errar, falta de urgência, desconfiança ou má experiência anterior. Você verá como identificar qual tipo está em jogo e como ajustar sua abordagem (mais prova, mais urgência, mais empatia) em vez de insistir no mesmo argumento.",
        duration: "10 min",
        status: "not_started",
        order: 1,
        scenarioSlug: "negociacao",
        characterId: "char-1",
      },
      {
        id: "mod-6-2",
        title: "Reframe e Ressignificação",
        objective: "Mudar a perspectiva do cliente",
        content:
          "Aqui você aprende a reformular a objeção de forma que o cliente veja por outro ângulo: de custo para investimento, de risco para oportunidade, de não agora para quando. O conteúdo traz exemplos de reframes que funcionam e como fazer isso sem soar manipulador.",
        duration: "15 min",
        status: "not_started",
        order: 2,
        scenarioSlug: "venda-b2b",
        characterId: "char-2",
      },
      {
        id: "mod-6-3",
        title: "Prova Social e Autoridade",
        objective: "Usar credenciais e referências",
        duration: "12 min",
        status: "not_started",
        order: 3,
        scenarioSlug: "fechamento",
        characterId: "char-3",
      },
      {
        id: "mod-6-4",
        title: "A Arte da Concessão",
        objective: "Quando e como ceder estrategicamente",
        duration: "13 min",
        status: "not_started",
        order: 4,
        scenarioSlug: "negociacao",
        characterId: "char-1",
      },
      {
        id: "mod-6-5",
        title: "Prática Intensiva",
        objective: "Roleplay de objeções difíceis",
        duration: "15 min",
        status: "not_started",
        order: 5,
        scenarioSlug: "negociacao",
        characterId: "char-2",
      },
    ],
  },
  {
    id: "track-3-3",
    slug: "objecoes-preco",
    title: "Lidando com Objeções de Preço",
    description: "Estratégias específicas para quando o cliente questiona o valor dos seus serviços, transformando objeção em oportunidade.",
    coverImage: trackImages.objecoes,
    estimatedTime: "45 min",
    difficulty: "intermediate",
    categoryId: "cat-3",
    progress: 0,
    tags: ["preço", "objeções", "valor"],
    modules: [
      {
        id: "mod-3-3-1",
        title: "Entendendo a Objeção de Preço",
        objective: "Por que clientes questionam preço",
        content:
          "Este módulo explica por que o cliente questiona preço: pode ser objeção real (orçamento), de valor (não vê benefício) ou de processo (precisa de aprovação). Você verá como distinguir cada caso com uma pergunta e como escolher a resposta certa em vez de descontar na hora.",
        duration: "10 min",
        status: "not_started",
        order: 1,
        scenarioSlug: "negociacao",
        characterId: "char-1",
      },
      {
        id: "mod-3-3-2",
        title: "Demonstrando Valor",
        objective: "Mostrar que o preço é justo",
        content:
          "Aqui você aprende a demonstrar valor antes de falar de preço: benefícios ligados às dores do cliente, comparação com alternativas e custo de não resolver. O conteúdo traz como quebrar o valor em custo por uso ou por período e frases que ajudam o cliente a enxergar o retorno.",
        duration: "15 min",
        status: "not_started",
        order: 2,
        scenarioSlug: "negociacao",
        characterId: "char-2",
      },
      {
        id: "mod-3-3-3",
        title: "Técnicas de Justificativa",
        objective: "Como defender seu preço",
        duration: "12 min",
        status: "not_started",
        order: 3,
        scenarioSlug: "negociacao",
        characterId: "char-3",
      },
      {
        id: "mod-3-3-4",
        title: "Prática de Preço",
        objective: "Roleplay de objeções de preço",
        duration: "8 min",
        status: "not_started",
        order: 4,
        scenarioSlug: "negociacao",
        characterId: "char-1",
      },
    ],
  },
  {
    id: "track-3-4",
    slug: "objecoes-tempo",
    title: "Objeções de Tempo e Disponibilidade",
    description: "Aprenda a lidar quando o cliente questiona tempo de espera, duração do serviço ou disponibilidade de horários.",
    coverImage: trackImages.objecoes,
    estimatedTime: "40 min",
    difficulty: "beginner",
    categoryId: "cat-3",
    progress: 0,
    tags: ["tempo", "objeções", "disponibilidade"],
    modules: [
      {
        id: "mod-3-4-1",
        title: "Gerenciando Expectativas",
        objective: "Comunicar tempo de forma clara",
        content:
          "O módulo ensina a comunicar tempo de espera e duração do serviço de forma que o cliente não se frustre: dar prazos realistas, avisar se houver atraso e explicar o que está incluído no tempo. Você verá scripts para diferentes situações e como evitar promessas que não pode cumprir.",
        duration: "10 min",
        status: "not_started",
        order: 1,
        scenarioSlug: "atendimento",
        characterId: "char-1",
      },
      {
        id: "mod-3-4-2",
        title: "Transformando Espera",
        objective: "Fazer o tempo de espera valer a pena",
        content:
          "Conteúdo sobre como transformar a espera em parte positiva da experiência: ambiente confortável, bebida, revistas ou breve conversa. Inclui como explicar ao cliente que a espera é sinal de qualidade e como oferecer alternativas de horário quando possível.",
        duration: "12 min",
        status: "not_started",
        order: 2,
        scenarioSlug: "atendimento",
        characterId: "char-2",
      },
      {
        id: "mod-3-4-3",
        title: "Alternativas de Horário",
        objective: "Oferecer soluções flexíveis",
        duration: "10 min",
        status: "not_started",
        order: 3,
        scenarioSlug: "atendimento",
        characterId: "char-3",
      },
      {
        id: "mod-3-4-4",
        title: "Prática de Tempo",
        objective: "Roleplay de objeções de tempo",
        duration: "8 min",
        status: "not_started",
        order: 4,
        scenarioSlug: "atendimento",
        characterId: "char-1",
      },
    ],
  },
  {
    id: "track-3-5",
    slug: "objecoes-qualidade",
    title: "Objeções sobre Qualidade",
    description: "Quando o cliente questiona a qualidade do serviço ou produto, aprenda a responder com confiança e credibilidade.",
    coverImage: trackImages.objecoes,
    estimatedTime: "50 min",
    difficulty: "intermediate",
    categoryId: "cat-3",
    progress: 0,
    tags: ["qualidade", "objeções", "credibilidade"],
    modules: [
      {
        id: "mod-3-5-1",
        title: "Demonstrando Expertise",
        objective: "Mostrar conhecimento e experiência",
        content:
          "Neste módulo você vê como demonstrar expertise sem soar arrogante: casos de sucesso, certificações, tempo de mercado e linguagem técnica na dose certa. Inclui quando usar cada tipo de prova e como responder a dúvidas sobre qualidade mantendo autoridade e acessibilidade.",
        duration: "15 min",
        status: "not_started",
        order: 1,
        scenarioSlug: "atendimento",
        characterId: "char-1",
      },
      {
        id: "mod-3-5-2",
        title: "Prova Social",
        objective: "Usar referências e depoimentos",
        content:
          "Aqui você aprende a usar depoimentos, avaliações e casos de clientes para reforçar qualidade. O conteúdo traz como escolher as melhores provas para cada objeção, como citar números e nomes sem exagero e como pedir referência ao cliente satisfeito para usar no futuro.",
        duration: "12 min",
        status: "not_started",
        order: 2,
        scenarioSlug: "fechamento",
        characterId: "char-2",
      },
      {
        id: "mod-3-5-3",
        title: "Garantias e Compromissos",
        objective: "Oferecer garantias que geram confiança",
        duration: "13 min",
        status: "not_started",
        order: 3,
        scenarioSlug: "atendimento",
        characterId: "char-3",
      },
      {
        id: "mod-3-5-4",
        title: "Prática de Qualidade",
        objective: "Roleplay de objeções de qualidade",
        duration: "10 min",
        status: "not_started",
        order: 4,
        scenarioSlug: "atendimento",
        characterId: "char-1",
      },
    ],
  },
  {
    id: "track-3-6",
    slug: "objecoes-avancado",
    title: "Objeções Avançadas",
    description: "Técnicas sofisticadas para lidar com objeções complexas e múltiplas, transformando resistência em aceitação.",
    coverImage: trackImages.persuasao,
    estimatedTime: "1h 10min",
    difficulty: "advanced",
    categoryId: "cat-3",
    progress: 0,
    tags: ["objeções", "avançado", "persuasão"],
    modules: [
      {
        id: "mod-3-6-1",
        title: "Múltiplas Objeções",
        objective: "Lidar com várias objeções simultâneas",
        content:
          "O módulo ensina a priorizar quando o cliente traz preço, tempo e qualidade ao mesmo tempo: qual tratar primeiro, como não entrar em modo defensivo e como usar uma objeção para reforçar a resposta da outra. Inclui exemplos de sequência de respostas que funcionam.",
        duration: "18 min",
        status: "not_started",
        order: 1,
        scenarioSlug: "negociacao",
        characterId: "char-1",
      },
      {
        id: "mod-3-6-2",
        title: "Objeções Emocionais",
        objective: "Reconhecer e lidar com objeções emocionais",
        content:
          "Aqui você aprende a reconhecer quando a objeção é emocional (medo, desconfiança, má experiência) e a responder com empatia antes de argumentos. O conteúdo traz como validar o sentimento do cliente, quando pedir mais detalhes e como propor um próximo passo que reduza o risco percebido.",
        duration: "20 min",
        status: "not_started",
        order: 2,
        scenarioSlug: "negociacao",
        characterId: "char-2",
      },
      {
        id: "mod-3-6-3",
        title: "Técnicas Avançadas",
        objective: "Frameworks sofisticados de resposta",
        duration: "17 min",
        status: "not_started",
        order: 3,
        scenarioSlug: "venda-b2b",
        characterId: "char-3",
      },
      {
        id: "mod-3-6-4",
        title: "Prática Avançada",
        objective: "Roleplay de objeções complexas",
        duration: "15 min",
        status: "not_started",
        order: 4,
        scenarioSlug: "negociacao",
        characterId: "char-1",
      },
    ],
  },
];

// Helper functions
export function getTracksByCategory(categoryId: string): LearningTrack[] {
  return learningTracks.filter((track) => track.categoryId === categoryId);
}

export function getFeaturedTracks(): LearningTrack[] {
  return learningTracks.filter((track) => track.featured);
}

export function getRecommendedTracks(limit: number = 4): LearningTrack[] {
  return learningTracks
    .filter((track) => track.badge === "recommended" || track.badge === "beginner" || track.progress === 0)
    .slice(0, limit);
}

export function getTrackById(id: string): LearningTrack | undefined {
  return learningTracks.find((track) => track.id === id);
}

export function getTrackBySlug(slug: string): LearningTrack | undefined {
  return learningTracks.find((track) => track.slug === slug);
}

export function getCategoryById(id: string): TrackCategory | undefined {
  return learningCategories.find((cat) => cat.id === id);
}

export function calculateTrackProgress(track: LearningTrack): number {
  const completed = track.modules.filter((m) => m.status === "completed").length;
  return Math.round((completed / track.modules.length) * 100);
}
