import type { 
  Roleplay, 
  UserMetrics, 
  LeaderboardEntry, 
  SessionFeedback, 
  TranscriptEntry, 
  RoleplayScenario,
  SessionAnalytics,
  SessionObjections,
  UserSessionHistory
} from "@/types";

export const mockScenarios: RoleplayScenario[] = [
  {
    id: "scenario-1",
    slug: "venda-b2b",
    name: "Venda B2B",
    description: "Pratique vendas business-to-business com decisores de diferentes setores e níveis hierárquicos.",
    icon: "💼",
    color: "#2E63CD",
    characters: [
      {
        id: "char-b2b-1",
        name: "Carlos Mendes",
        role: "Diretor de TI",
        company: "TechCorp",
        avatar: "https://i.pravatar.cc/150?u=carlos",
        personality: "Analítico, ocupado, cético mas aberto a soluções inovadoras",
        difficulty: "intermediate",
        context: "Empresa de 500 funcionários enfrentando problemas de segurança cibernética. Precisa justificar investimentos para a diretoria.",
        objectives: ["Estabelecer rapport", "Identificar dores técnicas", "Agendar demo"],
        voiceId: "voice-1",
      },
      {
        id: "char-b2b-2",
        name: "Patricia Costa",
        role: "CFO",
        company: "Industrial Corp",
        avatar: "https://i.pravatar.cc/150?u=patricia",
        personality: "Conservadora, analítica, focada em ROI e métricas financeiras",
        difficulty: "advanced",
        context: "Já viu várias propostas, exige dados concretos e cases de sucesso.",
        objectives: ["Apresentar ROI", "Responder objeções financeiras", "Conseguir próximo passo"],
        voiceId: "voice-4",
      },
      {
        id: "char-b2b-3",
        name: "Roberto Alves",
        role: "CEO",
        company: "StartupX",
        avatar: "https://i.pravatar.cc/150?u=roberto",
        personality: "Visionário, impaciente, quer resultados rápidos e inovação",
        difficulty: "intermediate",
        context: "Startup em crescimento buscando escalar operações rapidamente.",
        objectives: ["Demonstrar valor rápido", "Mostrar escalabilidade", "Fechar compromisso"],
        voiceId: "voice-3",
      },
    ],
  },
  {
    id: "scenario-2",
    slug: "atendimento",
    name: "Atendimento ao Cliente",
    description: "Treine habilidades de suporte e atendimento com clientes de diferentes perfis e situações.",
    icon: "🎧",
    color: "#10B981",
    characters: [
      {
        id: "char-atend-1",
        name: "Ana Beatriz",
        role: "Cliente Insatisfeita",
        company: "Consumidora Final",
        avatar: "https://i.pravatar.cc/150?u=anabeatriz",
        personality: "Frustrada, impaciente, já tentou resolver várias vezes",
        difficulty: "advanced",
        context: "Pedido atrasado há 10 dias, já ligou 3 vezes sem solução.",
        objectives: ["Acalmar o cliente", "Resolver o problema", "Reverter a insatisfação"],
        voiceId: "voice-5",
      },
      {
        id: "char-atend-2",
        name: "João Pedro",
        role: "Cliente com Dúvidas",
        company: "Novo Usuário",
        avatar: "https://i.pravatar.cc/150?u=joaopedro",
        personality: "Curioso, um pouco confuso, precisa de orientação clara",
        difficulty: "beginner",
        context: "Acabou de contratar o serviço e não sabe usar todas as funcionalidades.",
        objectives: ["Explicar funcionalidades", "Garantir entendimento", "Oferecer recursos adicionais"],
        voiceId: "voice-6",
      },
      {
        id: "char-atend-3",
        name: "Maria Clara",
        role: "Cliente Exigente",
        company: "Empresa Premium",
        avatar: "https://i.pravatar.cc/150?u=mariaclara",
        personality: "Assertiva, conhece seus direitos, espera atendimento VIP",
        difficulty: "intermediate",
        context: "Cliente de longa data que paga plano premium e espera prioridade.",
        objectives: ["Demonstrar valor premium", "Resolver rapidamente", "Manter fidelidade"],
        voiceId: "voice-7",
      },
      {
        id: "char-atend-4",
        name: "Lucas Ferreira",
        role: "Gerente de Operações",
        company: "LogiTech",
        avatar: "https://i.pravatar.cc/150?u=lucas",
        personality: "Pragmático, busca eficiência, valoriza parcerias de longo prazo",
        difficulty: "intermediate",
        context: "Customizado conforme briefing do administrador",
        objectives: ["Aplicar as técnicas específicas do seu playbook", "Praticar argumentos da sua oferta real", "Receber feedback contextualizado"],
        voiceId: "voice-5",
      },
    ],
  },
  {
    id: "scenario-3",
    slug: "negociacao",
    name: "Negociação",
    description: "Desenvolva técnicas de negociação com diferentes perfis de compradores e situações complexas.",
    icon: "🤝",
    color: "#F59E0B",
    characters: [
      {
        id: "char-neg-1",
        name: "Marina Silva",
        role: "Gerente de Compras",
        company: "Retail Plus",
        avatar: "https://i.pravatar.cc/150?u=marina",
        personality: "Direta, focada em resultados, sempre busca o melhor preço",
        difficulty: "intermediate",
        context: "Precisa de uma solução mas tem orçamento apertado. Compara com concorrentes.",
        objectives: ["Demonstrar valor", "Manter margem", "Fechar negócio"],
        voiceId: "voice-2",
      },
      {
        id: "char-neg-2",
        name: "Fernando Souza",
        role: "Diretor Comercial",
        company: "MegaDistribuidora",
        avatar: "https://i.pravatar.cc/150?u=fernando",
        personality: "Experiente, negociador duro, conhece o mercado",
        difficulty: "advanced",
        context: "Volume alto de compras, espera condições especiais e exclusividade.",
        objectives: ["Negociar volume", "Definir condições", "Estabelecer parceria"],
        voiceId: "voice-8",
      },
      {
        id: "char-neg-3",
        name: "Camila Rodrigues",
        role: "Compradora Técnica",
        company: "Indústria Tech",
        avatar: "https://i.pravatar.cc/150?u=camilarodrigues",
        personality: "Detalhista, precisa de especificações técnicas precisas",
        difficulty: "intermediate",
        context: "Avaliando fornecedores para projeto de longo prazo.",
        objectives: ["Apresentar especificações", "Demonstrar expertise", "Ganhar confiança técnica"],
        voiceId: "voice-9",
      },
    ],
  },
  {
    id: "scenario-4",
    slug: "cold-call",
    name: "Cold Call",
    description: "Pratique ligações frias para prospecção com diferentes receptividades e objeções iniciais.",
    icon: "📞",
    color: "#8B5CF6",
    characters: [
      {
        id: "char-cold-1",
        name: "Ricardo Gomes",
        role: "Gerente Ocupado",
        company: "Empresa Média",
        avatar: "https://i.pravatar.cc/150?u=ricardo",
        personality: "Muito ocupado, direto, tem pouco tempo disponível",
        difficulty: "intermediate",
        context: "Não conhece sua empresa, recebe muitas ligações de vendedores.",
        objectives: ["Captar atenção em 10s", "Gerar interesse", "Conseguir reunião"],
        voiceId: "voice-10",
      },
      {
        id: "char-cold-2",
        name: "Luciana Torres",
        role: "Assistente Executiva",
        company: "Corporação ABC",
        avatar: "https://i.pravatar.cc/150?u=luciana",
        personality: "Protetora, filtra ligações, precisa ser convencida",
        difficulty: "beginner",
        context: "Guarda a agenda do diretor, decide quem passa ou não.",
        objectives: ["Ultrapassar a barreira", "Descobrir decisor", "Agendar callback"],
        voiceId: "voice-11",
      },
      {
        id: "char-cold-3",
        name: "Marcos Oliveira",
        role: "Empresário Cético",
        company: "PME Solutions",
        avatar: "https://i.pravatar.cc/150?u=marcosoliveira",
        personality: "Desconfiado, já foi enganado antes, precisa de provas",
        difficulty: "advanced",
        context: "Dono de pequena empresa, cansado de promessas vazias.",
        objectives: ["Construir credibilidade", "Mostrar cases reais", "Agendar demonstração"],
        voiceId: "voice-12",
      },
    ],
  },
  {
    id: "scenario-5",
    slug: "fechamento",
    name: "Fechamento",
    description: "Treine técnicas de fechamento para converter leads quentes em clientes efetivos.",
    icon: "✅",
    color: "#EF4444",
    characters: [
      {
        id: "char-close-1",
        name: "Fernanda Lima",
        role: "Head de Marketing",
        company: "AgencyPro",
        avatar: "https://i.pravatar.cc/150?u=fernanda",
        personality: "Interessada mas precisa de aprovação superior",
        difficulty: "intermediate",
        context: "Gostou da proposta, mas precisa convencer o board.",
        objectives: ["Fornecer argumentos", "Ajudar na venda interna", "Definir próximos passos"],
        voiceId: "voice-6",
      },
      {
        id: "char-close-2",
        name: "André Martins",
        role: "Sócio-Diretor",
        company: "Consultoria Prime",
        avatar: "https://i.pravatar.cc/150?u=andremartins",
        personality: "Decidido mas quer última garantia antes de fechar",
        difficulty: "beginner",
        context: "Está convencido, só precisa do empurrão final.",
        objectives: ["Identificar última objeção", "Aplicar técnica de fechamento", "Confirmar o acordo"],
        voiceId: "voice-13",
      },
      {
        id: "char-close-3",
        name: "Juliana Castro",
        role: "Diretora de Operações",
        company: "LogiMaster",
        avatar: "https://i.pravatar.cc/150?u=juliana",
        personality: "Em cima do muro, comparando com concorrente",
        difficulty: "advanced",
        context: "Tem proposta do concorrente na mesa, precisa decidir hoje.",
        objectives: ["Diferenciar da concorrência", "Criar urgência", "Fechar o contrato"],
        voiceId: "voice-14",
      },
      {
        id: "char-close-4",
        name: "Patricia Costa",
        role: "CFO",
        company: "Industrial Corp",
        avatar: "https://i.pravatar.cc/150?u=patricia",
        personality: "Conservadora, analítica, precisa de dados para decidir",
        difficulty: "advanced",
        context: "Já viu a proposta, tem interesse mas não decidiu",
        objectives: ["Identificar o bloqueador final", "Usar técnica de fechamento apropriada", "Conseguir o compromisso ou próximo passo claro"],
        voiceId: "voice-4",
      },
    ],
  },
];

export const mockRoleplays: Roleplay[] = [
  {
    id: "1",
    title: "Primeira Abordagem: Decisor de TI",
    description: "Pratique a abordagem inicial com um diretor de TI de uma empresa de médio porte. Foco em identificar dores e qualificar o lead.",
    category: "behavioral",
    difficulty: "beginner",
    estimatedDuration: 10,
    scenarioSlug: "venda-b2b",
    agent: {
      id: "char-b2b-1",
      name: "Carlos Mendes",
      role: "Diretor de TI - TechCorp",
      avatar: "https://i.pravatar.cc/150?u=carlos",
      voiceId: "voice-1",
      personality: "Analítico, ocupado, cético mas aberto a soluções inovadoras",
      context: "Empresa de 500 funcionários enfrentando problemas de segurança cibernética",
    },
    objectives: [
      "Estabelecer rapport em menos de 30 segundos",
      "Identificar pelo menos 2 dores do prospect",
      "Agendar uma próxima reunião",
    ],
    advanced: {
      canAgentEndCall: false,
      maxDuration: 10,
      interruptionLevel: "low",
      agentMode: "balanced",
    },
    tags: ["prospecção", "TI", "B2B"],
    createdBy: "admin",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    title: "Lidando com Objeção de Preço",
    description: "Treine técnicas para contornar a objeção 'está muito caro' sem reduzir o preço. Foco em demonstrar valor.",
    category: "objection",
    difficulty: "intermediate",
    estimatedDuration: 15,
    scenarioSlug: "negociacao",
    agent: {
      id: "char-neg-1",
      name: "Marina Silva",
      role: "Gerente de Compras - Retail Plus",
      avatar: "https://i.pravatar.cc/150?u=marina",
      voiceId: "voice-2",
      personality: "Direta, focada em resultados, sensível a preço",
      context: "Precisa de uma solução mas tem orçamento limitado",
    },
    objectives: [
      "Entender o orçamento real disponível",
      "Reforçar o ROI da solução",
      "Apresentar opções de pagamento",
    ],
    objections: [
      { id: "obj-1", content: "O preço está muito acima do orçamento disponível", category: "price" },
      { id: "obj-2", content: "Preciso de mais tempo para avaliar outras opções", category: "timing" },
      { id: "obj-3", content: "Não sei se conseguirei aprovação da diretoria", category: "authority" },
    ],
    advanced: {
      canAgentEndCall: true,
      maxDuration: 15,
      interruptionLevel: "medium",
      agentMode: "challenging",
    },
    tags: ["objeções", "preço", "negociação"],
    createdBy: "admin",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "3",
    title: "Demonstração de Produto SaaS",
    description: "Conduza uma demo efetiva de software para um potencial cliente. Pratique como destacar features relevantes.",
    category: "technical",
    difficulty: "intermediate",
    estimatedDuration: 20,
    scenarioSlug: "venda-b2b",
    agent: {
      id: "char-b2b-3",
      name: "Roberto Alves",
      role: "CEO - StartupX",
      avatar: "https://i.pravatar.cc/150?u=roberto",
      voiceId: "voice-3",
      personality: "Visionário, impaciente, quer ver resultados rápidos",
      context: "Startup em crescimento buscando escalar operações",
    },
    objectives: [
      "Personalizar a demo para as necessidades do cliente",
      "Demonstrar 3 features principais",
      "Criar urgência para decisão",
    ],
    tags: ["demo", "SaaS", "startup"],
    createdBy: "admin",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "4",
    title: "Fechamento: Proposta Final",
    description: "Pratique técnicas de fechamento quando o prospect está em cima do muro. Supere as últimas hesitações.",
    category: "closing",
    difficulty: "advanced",
    estimatedDuration: 15,
    scenarioSlug: "fechamento",
    agent: {
      id: "char-close-4",
      name: "Patricia Costa",
      role: "CFO - Industrial Corp",
      avatar: "https://i.pravatar.cc/150?u=patricia",
      voiceId: "voice-4",
      personality: "Conservadora, analítica, precisa de dados para decidir",
      context: "Já viu a proposta, tem interesse mas não decidiu",
    },
    objectives: [
      "Identificar o bloqueador final",
      "Usar técnica de fechamento apropriada",
      "Conseguir o compromisso ou próximo passo claro",
    ],
    objections: [
      { id: "obj-4", content: "Preciso apresentar para o board antes de decidir", category: "authority" },
      { id: "obj-5", content: "O ROI ainda não está totalmente claro para mim", category: "need" },
      { id: "obj-6", content: "Temos uma proposta similar do seu concorrente", category: "competitor" },
    ],
    advanced: {
      canAgentEndCall: false,
      maxDuration: 15,
      interruptionLevel: "high",
      agentMode: "challenging",
    },
    tags: ["fechamento", "enterprise", "CFO"],
    createdBy: "admin",
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-10"),
  },
  {
    id: "5",
    title: "Role-play Personalizado: Seu Caso",
    description: "Cenário customizado baseado em um case real da sua empresa. Pratique situações do seu dia a dia.",
    category: "custom",
    difficulty: "intermediate",
    estimatedDuration: 15,
    scenarioSlug: "atendimento",
    agent: {
      id: "char-atend-4",
      name: "Lucas Ferreira",
      role: "Gerente de Operações - LogiTech",
      avatar: "https://i.pravatar.cc/150?u=lucas",
      voiceId: "voice-5",
      personality: "Pragmático, busca eficiência, valoriza parcerias de longo prazo",
      context: "Customizado conforme briefing do administrador",
    },
    objectives: [
      "Aplicar as técnicas específicas do seu playbook",
      "Praticar argumentos da sua oferta real",
      "Receber feedback contextualizado",
    ],
    tags: ["personalizado", "custom", "avançado"],
    createdBy: "admin",
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-02-15"),
  },
  {
    id: "6",
    title: "Recuperação de Lead Frio",
    description: "Reative um lead que não respondeu há 3 meses. Pratique como reengajar sem parecer insistente.",
    category: "behavioral",
    difficulty: "advanced",
    estimatedDuration: 10,
    scenarioSlug: "fechamento",
    agent: {
      id: "char-close-1",
      name: "Fernanda Lima",
      role: "Head de Marketing - AgencyPro",
      avatar: "https://i.pravatar.cc/150?u=fernanda",
      voiceId: "voice-6",
      personality: "Ocupada, recebe muitas ofertas, valoriza relevância",
      context: "Demonstrou interesse há 3 meses mas parou de responder",
    },
    objectives: [
      "Relembrar a conversa anterior sem ser invasivo",
      "Descobrir se o timing mudou",
      "Requalificar a oportunidade",
    ],
    tags: ["reativação", "follow-up", "leads frios"],
    createdBy: "admin",
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-02-20"),
  },
];

export const mockUserMetrics: UserMetrics = {
  userId: "user-1",
  totalSessions: 47,
  completedSessions: 42,
  averageScore: 78,
  totalPracticeTime: 840,
  streakDays: 5,
  badges: [
    {
      id: "badge-1",
      name: "Primeira Prática",
      description: "Completou seu primeiro role-play",
      icon: "🎯",
      earnedAt: new Date("2024-01-20"),
    },
    {
      id: "badge-2",
      name: "Consistência",
      description: "5 dias seguidos praticando",
      icon: "🔥",
      earnedAt: new Date("2024-02-15"),
    },
    {
      id: "badge-3",
      name: "Mestre das Objeções",
      description: "Score 90+ em role-play de objeções",
      icon: "💪",
      earnedAt: new Date("2024-02-18"),
    },
  ],
  weeklyProgress: [
    { week: "Semana 1", sessions: 8, averageScore: 65 },
    { week: "Semana 2", sessions: 10, averageScore: 72 },
    { week: "Semana 3", sessions: 12, averageScore: 78 },
    { week: "Semana 4", sessions: 12, averageScore: 82 },
  ],
};

export const mockLeaderboard: LeaderboardEntry[] = [
  {
    userId: "user-1",
    userName: "Ana Carolina",
    userAvatar: "https://i.pravatar.cc/150?u=ana",
    rank: 1,
    score: 94,
    sessionsCompleted: 58,
    improvement: 12,
  },
  {
    userId: "user-2",
    userName: "Pedro Santos",
    userAvatar: "https://i.pravatar.cc/150?u=pedro",
    rank: 2,
    score: 91,
    sessionsCompleted: 52,
    improvement: 8,
  },
  {
    userId: "user-3",
    userName: "Julia Oliveira",
    userAvatar: "https://i.pravatar.cc/150?u=julia",
    rank: 3,
    score: 88,
    sessionsCompleted: 45,
    improvement: 15,
  },
  {
    userId: "user-4",
    userName: "Marcos Lima",
    userAvatar: "https://i.pravatar.cc/150?u=marcos",
    rank: 4,
    score: 85,
    sessionsCompleted: 40,
    improvement: 5,
  },
  {
    userId: "user-5",
    userName: "Camila Rocha",
    userAvatar: "https://i.pravatar.cc/150?u=camila",
    rank: 5,
    score: 82,
    sessionsCompleted: 38,
    improvement: 10,
  },
];

export const mockFeedback: SessionFeedback = {
  id: "feedback-1",
  sessionId: "session-1",
  overallScore: 78,
  categories: [
    {
      name: "Tom de Voz",
      score: 8,
      maxScore: 10,
      feedback: "Bom tom conversacional, mas poderia variar mais a entonação para manter o engajamento.",
    },
    {
      name: "Estrutura da Argumentação",
      score: 7,
      maxScore: 10,
      feedback: "Argumentos lógicos, porém a sequência poderia ser mais estratégica.",
    },
    {
      name: "Conhecimento do Produto",
      score: 9,
      maxScore: 10,
      feedback: "Excelente domínio das features e benefícios do produto.",
    },
    {
      name: "Técnicas de Fechamento",
      score: 6,
      maxScore: 10,
      feedback: "Oportunidades de fechamento foram identificadas mas não aproveitadas.",
    },
    {
      name: "Tratamento de Objeções",
      score: 7,
      maxScore: 10,
      feedback: "Boa resposta às objeções, mas poderia fazer mais perguntas de esclarecimento.",
    },
  ],
  highlights: [
    {
      type: "positive",
      content: "Excelente rapport inicial - o prospect se sentiu à vontade rapidamente.",
    },
    {
      type: "positive",
      content: "Boa técnica de perguntas abertas para descobrir necessidades.",
    },
    {
      type: "positive",
      content: "Demonstrou conhecimento profundo do produto.",
    },
    {
      type: "improvement",
      content: "Perdeu uma oportunidade de fechamento quando o prospect mostrou interesse.",
    },
    {
      type: "improvement",
      content: "Poderia ter explorado mais a objeção de preço antes de responder.",
    },
  ],
  suggestions: [
    "Pratique técnicas de fechamento assumptivo para aproveitar sinais de compra.",
    "Ao ouvir uma objeção, faça pelo menos 2 perguntas de esclarecimento antes de responder.",
    "Varie mais o tom de voz para manter a energia da conversa.",
    "Prepare histórias de sucesso de clientes similares para usar como prova social.",
  ],
  summary: "Você demonstrou boas habilidades de relacionamento e conhecimento técnico. O principal ponto de desenvolvimento é aproveitar melhor os momentos de fechamento e aprofundar na exploração de objeções.",
  createdAt: new Date(),
};

export const mockTranscript: TranscriptEntry[] = [
  {
    id: "t-1",
    speaker: "agent",
    content: "Olá, boa tarde! Carlos Mendes falando.",
    timestamp: new Date(),
    sentiment: "neutral",
  },
  {
    id: "t-2",
    speaker: "user",
    content: "Boa tarde Carlos! Aqui é o João da SolutionTech. Tudo bem com você?",
    timestamp: new Date(),
    sentiment: "positive",
  },
  {
    id: "t-3",
    speaker: "agent",
    content: "Tudo bem, João. Olha, estou um pouco corrido aqui, mas pode falar.",
    timestamp: new Date(),
    sentiment: "neutral",
  },
  {
    id: "t-4",
    speaker: "user",
    content: "Entendo perfeitamente, vou ser breve. Vi que a TechCorp está expandindo e queria entender como vocês estão lidando com a segurança dos novos sistemas.",
    timestamp: new Date(),
    sentiment: "positive",
  },
  {
    id: "t-5",
    speaker: "agent",
    content: "É, segurança é uma preocupação constante. Tivemos alguns incidentes recentemente que nos deixaram em alerta.",
    timestamp: new Date(),
    sentiment: "neutral",
  },
  {
    id: "t-6",
    speaker: "user",
    content: "Posso imaginar. Que tipo de incidentes foram esses, se não for indiscrição perguntar?",
    timestamp: new Date(),
    sentiment: "positive",
  },
  {
    id: "t-7",
    speaker: "agent",
    content: "Tentativas de phishing com a equipe e um ransomware que quase pegou a gente.",
    timestamp: new Date(),
    sentiment: "negative",
  },
  {
    id: "t-8",
    speaker: "user",
    content: "Entendo, isso é bem sério mesmo. E como vocês estão se protegendo agora?",
    timestamp: new Date(),
    sentiment: "neutral",
  },
  {
    id: "t-9",
    speaker: "agent",
    content: "Olha, temos algumas ferramentas básicas, mas sei que precisamos de algo mais robusto. O problema é o orçamento...",
    timestamp: new Date(),
    sentiment: "neutral",
  },
  {
    id: "t-10",
    speaker: "user",
    content: "Totalmente compreensível. O custo de um incidente de segurança costuma ser muito maior que o investimento em prevenção. Posso te mostrar alguns números?",
    timestamp: new Date(),
    sentiment: "positive",
  },
  {
    id: "t-11",
    speaker: "agent",
    content: "Nossa solução está muito cara para o nosso orçamento atual.",
    timestamp: new Date(),
    sentiment: "negative",
  },
  {
    id: "t-12",
    speaker: "user",
    content: "Entendo sua preocupação com o investimento. Vamos falar sobre o retorno que você teria...",
    timestamp: new Date(),
    sentiment: "positive",
  },
  {
    id: "t-13",
    speaker: "agent",
    content: "Não sei se é o momento certo, talvez no próximo trimestre seja melhor.",
    timestamp: new Date(),
    sentiment: "neutral",
  },
  {
    id: "t-14",
    speaker: "user",
    content: "Hmm, ok. Podemos conversar depois então.",
    timestamp: new Date(),
    sentiment: "neutral",
  },
  {
    id: "t-15",
    speaker: "agent",
    content: "Já usamos uma solução similar da SecureNet.",
    timestamp: new Date(),
    sentiment: "neutral",
  },
  {
    id: "t-16",
    speaker: "user",
    content: "Entendo. Quais são os principais desafios que você enfrenta com essa solução?",
    timestamp: new Date(),
    sentiment: "positive",
  },
];

// Analytics Mockados
export const mockSessionAnalytics: SessionAnalytics = {
  sessionId: "session-1",
  talkListenRatio: {
    userTalkTime: 180,
    agentTalkTime: 120,
    ratio: 60,
  },
  speechMetrics: {
    wordsPerMinute: 145,
    averagePauseDuration: 2.5,
    fillerWordsCount: 8,
    fillerWords: ["eh", "tipo", "hmm"],
  },
  engagement: {
    longestMonologue: 45,
    interruptionsCount: 3,
    questionsAsked: 7,
  },
  recommendations: [
    "Reduza o uso de palavras de preenchimento para soar mais confiante",
    "Faça mais pausas estratégicas para dar espaço ao cliente pensar",
    "Aumente o número de perguntas abertas para descobrir mais necessidades",
  ],
};

// Objeções Mockadas
export const mockSessionObjections: SessionObjections = {
  sessionId: "session-1",
  objectionsRaised: [
    {
      id: "obj-1",
      type: "price",
      content: "Nossa solução está muito cara para o nosso orçamento atual.",
      userResponse: "Entendo sua preocupação com o investimento. Vamos falar sobre o retorno que você teria...",
      wasHandled: true,
      handlingTechnique: "ROI Focus",
      feedback: "Boa abordagem focando no retorno sobre investimento. Poderia ter aprofundado mais nos números específicos e casos de ROI de clientes similares.",
      transcriptEntryId: "t-11",
      timestamp: new Date("2026-01-21T10:15:00"),
    },
    {
      id: "obj-2",
      type: "timing",
      content: "Não sei se é o momento certo, talvez no próximo trimestre seja melhor.",
      userResponse: "Hmm, ok. Podemos conversar depois então.",
      wasHandled: false,
      feedback: "Objeção não foi adequadamente tratada. Faltou investigar o motivo real da hesitação e criar senso de urgência. Sempre pergunte 'O que mudaria no próximo trimestre?' para entender a real objeção.",
      transcriptEntryId: "t-13",
      timestamp: new Date("2026-01-21T10:18:00"),
    },
    {
      id: "obj-3",
      type: "competitor",
      content: "Já usamos uma solução similar da SecureNet.",
      userResponse: "Entendo. Quais são os principais desafios que você enfrenta com essa solução?",
      wasHandled: true,
      handlingTechnique: "Discovery Questions",
      feedback: "Excelente! Pergunta investigativa que revelou pain points com o concorrente. Continue explorando gaps entre o que têm e o que precisam.",
      transcriptEntryId: "t-15",
      timestamp: new Date("2026-01-21T10:22:00"),
    },
  ],
  objectionsHandled: 2,
  objectionsNotHandled: 1,
  handlingQuality: "good",
  suggestions: [
    "Pratique técnicas para objeções de timing (urgência, custo de não agir)",
    "Sempre investigue o 'porquê' antes de aceitar uma objeção passivamente",
    "Continue usando perguntas abertas para descobrir necessidades ocultas",
    "Prepare 3-4 casos de sucesso específicos para usar como prova social",
  ],
};

// Histórico de Sessões Mockado
export const mockUserSessionHistory: UserSessionHistory = {
  userId: "user-1",
  sessions: [
    {
      sessionId: "session-5",
      roleplayTitle: "Cold Call - Tech Startup",
      date: new Date("2026-01-20"),
      score: 82,
      duration: 420,
      category: "behavioral",
    },
    {
      sessionId: "session-4",
      roleplayTitle: "Lidando com Objeção de Preço",
      date: new Date("2026-01-18"),
      score: 78,
      duration: 540,
      category: "objection",
    },
    {
      sessionId: "session-3",
      roleplayTitle: "Demonstração de Produto SaaS",
      date: new Date("2026-01-15"),
      score: 85,
      duration: 720,
      category: "technical",
    },
    {
      sessionId: "session-2",
      roleplayTitle: "Primeira Abordagem: Decisor de TI",
      date: new Date("2026-01-12"),
      score: 72,
      duration: 360,
      category: "behavioral",
    },
    {
      sessionId: "session-1",
      roleplayTitle: "Fechamento: Proposta Final",
      date: new Date("2026-01-10"),
      score: 76,
      duration: 480,
      category: "closing",
    },
  ],
  overallStats: {
    totalSessions: 47,
    averageScore: 78,
    improvement: 15,
    bestCategory: "Técnico",
    weakestCategory: "Objeções",
  },
};

// Áudio Mockado (URL de exemplo)
export const mockAudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3";
